name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_mirrors:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install apt-mirror-updater
        run: pip install apt-mirror-updater
      - name: Update Mirror List
        run: |
          cat ubuntu.list
          apt-mirror-updater -l > ubuntu.list
          cat ubuntu.list
      - name: Commit files
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: main
          files: ubuntu.list
          commit-message: '[skip ci] Automatic update of ubuntu.list'